# Generated by Django 5.0.1 on 2024-02-05 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('state', models.CharField(choices=[('neuf', 'Neuf'), ('use', 'Usé'), ('reparable', 'Réparable'), ('casse', 'Cassé')], default='neuf', max_length=20)),
                ('power', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('modification_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(choices=[('light', 'Light'), ('son', 'Son'), ('structure', 'Structure'), ('autre', 'Autre')], max_length=20)),
                ('creation', models.DateTimeField(auto_now=True)),
                ('removed', models.DateTimeField(blank=True, null=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
