# Generated by Django 5.0.1 on 2024-02-04 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('modification_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('creation', models.DateTimeField(auto_now=True)),
                ('removed', models.DateTimeField(blank=True, null=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
