# Generated by Django 5.0.1 on 2024-02-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('light', 'Light'), ('son', 'Son'), ('structure', 'Structure'), ('autre', 'Autre')], default='autre', max_length=20),
            preserve_default=False,
        ),
    ]
