# Generated by Django 5.0.1 on 2024-02-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_item_creation_authtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
