# Generated by Django 5.0.3 on 2024-03-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="state",
            field=models.CharField(
                choices=[
                    ("neuf", "Neuf"),
                    ("bien", "Bien"),
                    ("use", "Usé"),
                    ("reparable", "Réparable"),
                    ("casse", "Cassé"),
                ],
                default="neuf",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("son", "Son"),
                    ("structure", "Structure"),
                    ("autre", "Autre"),
                    ("elec", "Elec"),
                    ("secu", "Secu"),
                ],
                max_length=20,
            ),
        ),
    ]
