# Generated by Django 5.0.1 on 2024-02-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='state',
            field=models.CharField(choices=[('neuf', 'Neuf'), ('use', 'Usé'), ('reparable', 'Réparable'), ('casse', 'Cassé')], default='neuf', max_length=20),
        ),
    ]
