# Generated by Django 5.0.1 on 2024-02-05 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_item_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='power',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
