# Generated by Django 5.0.3 on 2024-03-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_item_state_alter_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
