# Generated by Django 5.0.3 on 2024-03-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_item_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="pretable",
            field=models.BooleanField(default=False),
        ),
    ]
